### PR TITLE
Tight mode was failing for heading levels greater than 2

### PR DESCRIPTION
**Pull request by gkatsev**
This PR updates the test case to fail with the current version of mdast-util-toc.
I've already opened a PR against mdast-util-toc to fix the issue: https://github.com/BarryThePenguin/mdast-util-toc/pull/3

### CODE REVIEW

**Comment by wooorm** [comment]
Cool, thanks. I’ll merge this once @BarryThePenguin publishes a new release!

Thanks for finding this!

**Comment by gkatsev** [comment]
Happy to help!

**Comment by BarryThePenguin** [comment]
published

heads up though, I'm gonna release v3 and drop node v0.10 support similar to `remark-toc

**Comment by wooorm** [comment]
Thanks both!

**Pull request merged**
